version: '3'
services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: jjrmanzano/amazing-sentences-nginx:testing
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - 'var-www-html-testing:/var/www/html'
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
            timeout: 10s
        depends_on:
            - laravel
    laravel:
        build:
            context: .
            dockerfile: ./docker/8.1/Dockerfile.testing
            args:
                WWWGROUP: '${WWWGROUP:-www-data}'
        image: jjrmanzano/amazing-sentences-laravel:testing
        ports:
            - '8000:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER:-sail}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'coverage'
            LARAVEL_ENV_ENCRYPTION_KEY: '${LARAVEL_ENV_ENCRYPTION_KEY:-}'
        volumes:
            - 'var-www-html-testing:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
            - meilisearch
            - mailhog
    pgsql:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql-testing:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis-testing:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sail-meilisearch-testing:/meili_data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    var-www-html-testing:
        driver: local
    sail-pgsql-testing:
        driver: local
    sail-redis-testing:
        driver: local
    sail-meilisearch-testing:
        driver: local
