version: '3'
services:
    pgsql:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: 'password'
            POSTGRES_DB: 'testing'
            POSTGRES_USER: 'sail'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - 'sail-pgsql-testing:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "testing", "-U", "sail"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis-testing:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_ENV: 'production'
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY:-meilisearch_key}'
            MEILI_NO_ANALYTICS: true
        volumes:
            - 'sail-meilisearch-testing:/meili_data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    laravel:
        build:
            context: .
            dockerfile: ./docker/8.1/Dockerfile.testing
        image: jjrmanzano/amazing-sentences-laravel:testing
        ports:
            - '8000:8000'
        environment:
            WWWUSER: '${WWWUSER:-sail}'
            LARAVEL_SAIL: 1
        volumes:
            - 'laravel-logs-testing:/var/www/html/storage/logs'
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8000 || exit 1"]
            timeout: 5s
        depends_on:
            - pgsql
            - redis
            - meilisearch
            - mailhog
        restart: on-failure
        command: ["wait-for-it.sh", "pgsql:5432", "--strict", "--", "start-container.testing"]
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: jjrmanzano/amazing-sentences-nginx:testing
        ports:
            - '${APP_PORT:-80}:80'
            - '443:443'
        networks:
            - sail
        depends_on:
            - laravel
        restart: on-failure
        command: ["wait-for-it.sh", "laravel:8000", "--strict", "--", "startup.sh"]
networks:
    sail:
        driver: bridge
volumes:
    laravel-logs-testing:
        driver: local
    sail-pgsql-testing:
        driver: local
    sail-redis-testing:
        driver: local
    sail-meilisearch-testing:
        driver: local
