version: '3'
services:
    pgsql:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-amazing_sentences}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'sail-pgsql-production:/var/lib/postgresql/data'
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-amazing_sentences}", "-U", "${DB_USERNAME:-sail}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis-production:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_ENV: 'production'
            MEILI_MASTER_KEY: '${MEILISEARCH_KEY:-meilisearch_key}'
            MEILI_NO_ANALYTICS: true            
        volumes:
            - 'sail-meilisearch-production:/meili_data'
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
            retries: 3
            timeout: 5s
    laravel:
        build:
            context: .
            dockerfile: ./docker/8.1/Dockerfile.production
        image: jjrmanzano/amazing-sentences-laravel:latest
        ports:
            - '8000:8000'
        environment:
            WWWUSER: '${WWWUSER:-sail}'
            LARAVEL_SAIL: 1
            LARAVEL_ENV_ENCRYPTION_KEY: '${LARAVEL_ENV_ENCRYPTION_KEY:-}'
        volumes:
            - 'laravel-logs-production:/var/www/html/storage/logs'
        healthcheck:
            test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8000 || exit 1"]
            timeout: 5s
        depends_on:
            - pgsql
            - redis
            - meilisearch
        restart: on-failure
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: jjrmanzano/amazing-sentences-nginx:latest
        ports:
            - '80:80'
            - '443:443'
        healthcheck:
            test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
            timeout: 10s
        depends_on:
            - laravel
        restart: on-failure
volumes:
    laravel-logs-production:
        driver: local
    sail-pgsql-production:
        driver: local
    sail-redis-production:
        driver: local
    sail-meilisearch-production:
        driver: local
