name: Continous Delivery - Production Build, Tag and Publish to Docker Hub

on:
  workflow_call:

jobs:
  build-and-publish:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_64ecdce048654bebaecebf4d3d41c4c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0e31cadfd7f4b5a93a0be483bd95de7 }}

    - name: Build optimized bundle for production
      run: docker compose -f docker-compose.production.yml build

    - name: Tag and Push nginx:latest
      run: docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64ecdce048654bebaecebf4d3d41c4c5 }}/amazing-sentences-nginx:latest
    
    - name: Tag and Push laravel:latest
      run: docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_64ecdce048654bebaecebf4d3d41c4c5 }}/amazing-sentences-laravel:latest
        