name: Continous Integration - Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_64ecdce048654bebaecebf4d3d41c4c5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0e31cadfd7f4b5a93a0be483bd95de7 }}

    - name: Start application
      run: docker compose -f docker-compose.testing.yml up --wait

    - name: Change directory into application files
      run: cd /var/www/html

    - name: Linter
      run: ./vendor/bin/pint --test

    - name: Tests
      run: php artisan test --parallel --coverage --min=50.0

  continous-delivery:
    needs: build-and-test
    uses: ./.github/workflows/continuous-delivery.yml
    secrets: inherit
